name: Update Weather

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch weather data
        run: |
          TIMESTAMP=$(date +%s)

          PARAMS="api-key${{ secrets.WL_API_KEY }}station-id${{ secrets.WL_STATION_ID }}t${TIMESTAMP}"

          SIGNATURE=$(echo -n $PARAMS | openssl dgst -sha256 -hmac ${{ secrets.WL_API_SECRET }} | sed 's/^.* //')

          URL="https://api.weatherlink.com/v2/current/${{ secrets.WL_STATION_ID }}?api-key=${{ secrets.WL_API_KEY }}&t=${TIMESTAMP}&api-signature=${SIGNATURE}"

          curl -s "$URL" -o raw.json

      - name: Extract data
        run: |
          jq '{
            temperature: .sensors[0].data[0].temp,
            humidity: .sensors[0].data[0].hum,
            wind: .sensors[0].data[0].wind_speed_avg_last_1_min
          }' raw.json > weather.json

      - name: Commit weather.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add weather.json
          git commit -m "Update weather" || echo "No changes"
          git push
